name: CI/CD S3 Deploy via OIDC

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    # Required for the OIDC token exchange
    permissions:
      id-token: write   # Allows requesting the JWT ID token from GitHub OIDC provider
      contents: read    # Allows checking out the repo code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug OIDC Token Claims
        run: |
          # Fetch the raw token from GitHub's OIDC endpoint
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          # Decode the payload
          echo "Token payload:"
          echo "$TOKEN" | jq -R 'split(".") | .[1] | @base64d | fromjson'

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify Assumed Identity
        run: |
          aws sts get-caller-identity

      - name: Sync static files to S3
        run: |
          aws s3 sync ./public s3://${{ secrets.S3_BUCKET_NAME }}/ --delete